### PR TITLE
(WIP) Add tsunami model from Ch 2

### PR DESCRIPTION
**Pull request by littlewatkins**
Pull Request
========
Addresses #7 

This pull request is for the model developed in Chapter 2 of the Modern Fortran book. It's a good place to start doing the basic unit tests and checking what parts of our stuff works.

### CODE REVIEW

**Comment by littlewatkins** [comment]
I won't add more to it until later this weekend, but I wanted to get the program file started.

**Comment by knbarton** [comment]
I think this is a good start with the constants, but I think we should decide on exactly which parts of the tsunami code we'll be using. For example, I was thinking of taking inspiration from their "final" version (https://github.com/modern-fortran/tsunami/tree/master/src/final). There's a lot of stuff in there that we shouldn't need, but maybe we could have a module for doing to centered difference, a module for initialization, etc. I was planning to get some of that working today.

**Comment by littlewatkins** [comment]
Ah ok! That sounds good. I'm struggling to get a testing framework to work. I need to email Prof. Kochunas because his help getting his code testing framework to work. But from what I've seen of his, and now comparing the final tsunami code, I think they will work well together. Just have to get over this initial hump.

**Comment by knbarton** [comment]
I did see some of the info you posted in the other thread about the testing frameworks. It looked a bit confusing to me, so I'll try to dig through it a bit myself to see what is going on. In the meantime, I think I got the very basic version of the model running (no parallelism or anything) that I'll put in a pull request for soon, so maybe we could start with some really simple tests for what's in there at the moment, and worry about getting the other testing up and running after.

**Comment by littlewatkins** [comment]
Yeah a lot of what I put in the thread was for me to keep track of things. I wish I had something working. That would be better haha. I think for Prof. Kochunas's Futility testing structure, I'm just missing a couple things; I'm thinking possibly code from his repo. The test I'm trying to get to run is a example test basically. Just adds 2 and 2 to get 4. Mostly trying to verify my understanding of the testing structure before writing some for the model.

Sweet! Yes a working model will be good to work with.

**Comment by littlewatkins** [comment]
I'm closing this pull request now that the main model has been created.

**Pull request closed without merging**
