### PR TITLE
Add file structure to the code (issue #9)

### PR DESCRIPTION
**Pull request by knbarton**
This adds a src directory which contains all of the fortran and python code. Within src, there is a model directory which will contain the fortran code and a processing directory, which will contain the python code for processing. The script run.py will be a wrapper script which runs both the model and the processing.

### CODE REVIEW

**Comment by knbarton** [comment]
Let me know what you think about having this kind of structure for the code.

**Comment by knbarton** [comment]
I switched this to a draft pull request because I'm still thinking through it a little bit and I'd be happy to take some feedback in the meantime.

**Review by littlewatkins — APPROVED** [review]
This looks good to me! I think it's a good start

**Comment by knbarton** [comment]
I will go ahead and merge this so that we have a starting point. As we add things, we might change the structure a bit but that's okay.

**Pull request merged**
